[[_orcl.datasource]]
= Oracle Pooling DataSource
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

Oracle provides an advanced DataSource implementation that has some unique features.
It provides connection pooling and it is required when using "Fast Connection Failover" for RAC.

[[_orcl.datasource.1]]
== Configuration using the traditional <bean> element

We'll start by looking at a very basic DataSource configuration using the traditional <bean> element.

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
	   xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/context
       https://www.springframework.org/schema/context/spring-context-3.0.xsd">

    <bean id="dataSource" class="oracle.jdbc.pool.OracleDataSource" destroy-method="close"> 
        <property name="URL" value="${jdbc.url}" /> 
        <property name="user" value="${jdbc.username}"/> 
        <property name="password" value="${jdbc.password}"/> 
        <property name="connectionCachingEnabled" value="true"/> 
    </bean>

    <context:property-placeholder location="classpath:jdbc.properties"/> 

</beans>
----
// <calloutlist>
//         <callout arearefs="datasource.class">
//           <para>Here we specify the <classname>DataSource</classname>
//           implementation class as the
//           <classname>OracleDataSource</classname>.</para>
//         </callout>
// 
//         <callout arearefs="datasource.url">
//           <para>We specify the URL using the <classname>URL</classname>
//           property. Note that it is upper case in this implementation while it
//           is lower case in most other <classname>DataSource</classname>
//           implementations.</para>
//         </callout>
// 
//         <callout arearefs="datasource.username">
//           <para>The user name is specified using the
//           <classname>user</classname> property.</para>
//         </callout>
// 
//         <callout arearefs="datasource.password">
//           <para>The password is specified using the
//           <classname>password</classname> property.</para>
//         </callout>
// 
//         <callout arearefs="datasource.cache">
//           <para>The connection caching must be enabled explicitly using the
//           <classname>connectionCachingEnabled</classname> property.</para>
//         </callout>
// 
//         <callout arearefs="datasource.propertyPlaceholder">
//           <para>The property place holders will be filled in using this
//           <classname>&lt;context:property-placeholder&gt;</classname> element
//           from the context namespace.</para>
//         </callout>
//       </calloutlist>


[[_orcl.datasource.2]]
== Using the "orcl" namespace to configure theOracleDataSource

The new "orcl" namespace contains a [class]``pooling-data-source`` element used for easy configuration of the [class]``OracleDataSource``.
We will show several ways this element can be used and we will start with a basic one that can replace the traditional <bean> element configuration used above.

When using the [class]``pooling-data-source`` element connection caching is enabled by default and must explicitly be turned off using the [class]``connection-caching-enabled`` attribute if you don't want to use this pooling support.

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:orcl="http://www.springframework.org/schema/data/orcl" 
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/context
       https://www.springframework.org/schema/context/spring-context-3.0.xsd
       http://www.springframework.org/schema/data/orcl 
       https://www.springframework.org/schema/data/orcl/spring-data-orcl-1.0.xsd">

    <orcl:pooling-datasource id="dataSource"
        url="${jdbc.url}" username="${jdbc.username}" password="${jdbc.password}"/> 

    <context:property-placeholder location="classpath:jdbc.properties"/> 

</beans>
----
// <calloutlist>
//         <callout arearefs="datasource2.ns">
//           <para>Here we specify the reference to the
//           <classname>orcl</classname> schema.</para>
//         </callout>
// 
//         <callout arearefs="datasource2.xsd">
//           <para>We also specify the location for the
//           <classname>orcl</classname> schema.</para>
//         </callout>
// 
//         <callout arearefs="datasource2.properties">
//           <para>The properties needed to connect to the database in this
//           example are <classname>url</classname>,
//           <classname>username</classname> and <classname>password</classname>.
//           The <classname>url</classname> property could also be specifiec as
//           <classname>URL</classname> and the <classname>username</classname>
//           property could be specifed as <classname>user</classname>.</para>
//         </callout>
// 
//         <callout arearefs="datasource2.propertyPlaceholder">
//           <para>Just as in the previous example, the property place holders
//           will be filled in using this
//           <classname>&lt;context:property-placeholder&gt;</classname> element
//           from the context namespace.</para>
//         </callout>
//       </calloutlist>


[[_orcl.datasource.3]]
== Using a properties file directly for connection properties

We used a [class]``property-placeholder`` in the previous example to provide connection properties.
We can also read the properties directly from a properties file without using placeholders.
This is done by using a [class]``properties-location`` attribute specifying the location of the properties file.

[NOTE]
====
When you specify properties using a property file there are two basic properties, url and username, where you can use the Oracle property name or the name traditionally used by Spring developers.
For url we also accept URL and for username we also accept user.
====

We will use the following property file named [path]_orcl.properties_ and we will place it at the root of the classpath.

[source]
----
url=jdbc:oracle:thin:@//maui:1521/xe
username=spring
password=spring
----

Once we have this file in place we can reference it from our [class]``pooling-data-source`` entry and omit the property plceholder declarations for any properties provided in this file.

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:orcl="http://www.springframework.org/schema/data/orcl"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/context
       https://www.springframework.org/schema/context/spring-context-3.0.xsd
       http://www.springframework.org/schema/data/orcl
       https://www.springframework.org/schema/data/orcl/spring-data-orcl-1.0.xsd">

    <orcl:pooling-datasource id="dataSource" 
        properties-location="classpath:orcl.properties"/> 

</beans>
----
// <calloutlist>
//         <callout arearefs="datasource3.properties">
//           <para>The <classname>pooling-datasource</classname> with the
//           <classname>properties-location</classname> specified. The
//           <classname>URL</classname>, <classname>user</classname> and
//           <classname>password</classname> properties will be read from the
//           provided properties file.</para>
//         </callout>
//       </calloutlist>

You can even remove the [class]``properties-location`` attribute as long as you use the default location and name which is a file named [path]_orcl.properties_ at the root of the classpath.

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:orcl="http://www.springframework.org/schema/data/orcl"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/context
       https://www.springframework.org/schema/context/spring-context-3.0.xsd
       http://www.springframework.org/schema/data/orcl
       https://www.springframework.org/schema/data/orcl/spring-data-orcl-1.0.xsd">

    <orcl:pooling-datasource id="dataSource"/> 

</beans>
----
// <calloutlist>
//         <callout arearefs="datasource4.properties">
//           <para>The <classname>pooling-datasource</classname> without
//           properties or the <classname>properties-location</classname>
//           specified. We are relying on the default properties file name and
//           location.</para>
//         </callout>
//       </calloutlist>


[[_orcl.datasource.4]]
== Additional connection and cache properties

It's sometimes necessary to provide additional connection properties to control how the database access is configured.
There are several ways you can provide these properties and they are outlined below.

[[_orcl.datasource.4.1]]
=== Using the property file for additional connectionproperties

We can provide additional connection properties by ust adding them to the properties file we used in the example above.

[source]
----
url=jdbc:oracle:thin:@//maui:1521/xe
username=spring
password=spring
processEscapes=false
----

Any properties specified in addition to the standard URL/url, user/username and password will be used for configuring the [class]``OracleDataSource``.

We can also use a prefix for the connection properties.
This can be useful if the properties file contain other properties like connection cache properties.
We will see how these additional properties are used later on.

[source]
----
conn.url=jdbc:oracle:thin:@//maui:1521/xe
conn.username=spring
conn.password=spring
conn.processEscapes=false
----

The prefix must be specified in the [class]``pooling-data-source`` element configuration.
It is specified using the [class]``connection-properties-prefix`` attribute.

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:orcl="http://www.springframework.org/schema/data/orcl"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/context
       https://www.springframework.org/schema/context/spring-context-3.0.xsd
       http://www.springframework.org/schema/data/orcl
       https://www.springframework.org/schema/data/orcl/spring-data-orcl-1.0.xsd">

    <orcl:pooling-datasource id="dataSource" 
        connection-properties-prefix="conn" 
        properties-location="classpath:orcl.properties"/>

</beans>
----
// <calloutlist>
//           <callout arearefs="datasource.4.1.prefix">
//             <para>The <classname>connection-properties-prefix</classname> is
//             specified here.</para>
//           </callout>
//         </calloutlist>


[[_orcl.datasource.4.2]]
=== Using the property file for additional cache properties

We can also specify connection cache properties in the properties file.
We must use a prefix for these connection cache properties to distinguish them from the regular connection properties.
In this example we are using "cache" as the prefix.

[source]
----
conn.url=jdbc:oracle:thin:@//maui:1521/xe
conn.username=spring
conn.password=spring
conn.processEscapes=false
cache.InitialLimit=10
----

The connection cache prefix must be specified using the [class]``connection-cache-properties-prefix`` attribute.

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:orcl="http://www.springframework.org/schema/data/orcl"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/context
       https://www.springframework.org/schema/context/spring-context-3.0.xsd
       http://www.springframework.org/schema/data/orcl
       https://www.springframework.org/schema/data/orcl/spring-data-orcl-1.0.xsd">

    <orcl:pooling-datasource id="dataSource" 
        connection-properties-prefix="conn"
        connection-cache-properties-prefix="cache" 
        properties-location="classpath:orcl.properties"/>

</beans>
----
// <calloutlist>
//           <callout arearefs="datasource.4.2.prefix">
//             <para>The
//             <classname>connection-cache-properties-prefix</classname> is
//             specified here.</para>
//           </callout>
//         </calloutlist>


[[_orcl.datasource.4.3]]
=== Using "connection-properties" element for additional connectionproperties

The connection properties can be specified using the [class]``connection-properties`` element.

[NOTE]
====
If you specify a [class]``connection-properties`` element then any connection properties specified in a property file other than the basic url, username and password will not be used.
====

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:orcl="http://www.springframework.org/schema/data/orcl"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/context
       https://www.springframework.org/schema/context/spring-context-3.0.xsd
       http://www.springframework.org/schema/data/orcl
       https://www.springframework.org/schema/data/orcl/spring-data-orcl-1.0.xsd">

    <orcl:pooling-datasource id="dataSource" 
        properties-location="classpath:orcl.properties">
        <orcl:connection-properties>
            processEscapes=false 
        </orcl:connection-properties>
    </orcl:pooling-datasource>

</beans>
----
// <calloutlist>
//           <callout arearefs="datasource.4.3.prop">
//             <para>The connection properties are specified here.</para>
//           </callout>
//         </calloutlist>


[[_orcl.datasource.4.4]]
=== Using "connection-cache-properties" element for additional cacheproperties

The connection cache properties can be specified using the [class]``connection-cache-properties`` element.

[NOTE]
====
If you specify a [class]``connection-cache-properties`` element then any connection cache properties specified in a property file will not be used.
====

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:orcl="http://www.springframework.org/schema/data/orcl"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/context
       https://www.springframework.org/schema/context/spring-context-3.0.xsd
       http://www.springframework.org/schema/data/orcl
       https://www.springframework.org/schema/data/orcl/spring-data-orcl-1.0.xsd">

    <orcl:pooling-datasource id="dataSource" 
        properties-location="classpath:orcl.properties">
        <orcl:connection-properties>
            processEscapes=false
        </orcl:connection-properties>
        <orcl:connection-cache-properties>
            InitialLimit=10 
        </orcl:connection-cache-properties>
    </orcl:pooling-datasource>

</beans>
----
// <calloutlist>
//           <callout arearefs="datasrce.4.4.prop">
//             <para>The connection cache properties are specified here.</para>
//           </callout>
//         </calloutlist>


[[_orcl.datasource.4.5]]
=== Using "username-connection-proxy" element for proxyconnections

The Oracle JDBC driver provides proxy authentication.
This means that you can configure a connection pool using a proxy user account with limited rights.
Then during the connection process you would specify the actual username for the end user.
This username must be configured to allow a proxy connection through the user proxy ("grant connect through proxyuser"). See <<_connection>> for more details on this usage.

Connection proxy authentication is configured using the [class]``username-connection-proxy`` element.
You also need to provide a user name provider that implements the [class]``ConnectionUsernameProvider`` interface.
This interface has a single method named [class]``getUserName`` that should return the username for the current end user to be connected via the proxy user.

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:orcl="http://www.springframework.org/schema/data/orcl"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/context
       https://www.springframework.org/schema/context/spring-context-3.0.xsd
       http://www.springframework.org/schema/data/orcl
       https://www.springframework.org/schema/data/orcl/spring-data-orcl-1.0.xsd">

    <orcl:pooling-datasource id="dataSource" 
        properties-location="classpath:orcl.properties">
        <orcl:username-connection-proxy connection-context-provider="usernameProvider"/> 
    </orcl:pooling-datasource>

    <bean id="usernameProvider" class="org.springframework.data.jdbc.test.CurrentUsernameProvider"/>

</beans>
----
// <calloutlist>
//           <callout arearefs="datasource.4.5.prop">
//             <para>The connection proxy username provider is specified
//             here.</para>
//           </callout>
//         </calloutlist>


[[_orcl.datasource.options]]
== Summary of configuration options for the"pooling-data-source"

The [class]``pooling-data-source`` element has the following attributes:



.`<pooling-data-source>` attributesettings
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required
| Default
| Description

|``url``
|Yes
|
|The url to be used for connecting to the database. Can be
              provided in a property file. Alternate property name is `URL`

|``username``
|No
|
|The user name used to connect. Can be provided in a
              property file. Alternate property name is `user`

|``password``
|No
|
|The password used to connect. Can be provided in a
              property file.

|``connection-caching-enabled``
|No
|``true``
|Is connection caching enabled?

|``fast-connection-failover-enabled``
|No
|``false``
|Is the fast connection failover feature enabled?

|``ONS-configuration``
|No
|
|The ONS configuration string.

|``properties-location``
|No
|
|The location of a properties file containing key-value
              pairs for the connection and connection cache environment using
              a specific prefix to separate connection cache properties from
              connection properties (in standard Properties format, namely
              'key=value' pairs). If no location is specified a properties
              file located at `classpath:orcl.properties`
              will be used if found.

|``connection-properties-prefix``
|No
|
|The prefix that is used for connection properties
              provided in the property file.

|``connection-cache-properties-prefix``
|No
|
|The prefix that is used for connection cache properties
              provided in the property file.
|===

The [class]``pooling-data-source`` element has the following child elements:



.`<pooling-data-source>` childelements
[cols="1,1", options="header"]
|===
| Element
| Description

|``connection-properties``
|The newline-separated, key-value pairs for the connection
              properties (in standard Properties format, namely 'key=value'
              pairs)

|``connection-cache-properties``
|The newline-separated, key-value pairs for the
              connection-cache-properties (in standard Properties format,
              namely 'key=value' pairs)

|``username-connection-proxy``
|The configuration of a proxy authentication using a
              connection context provider
|===